armadaproject/armada-operator

.golangci.yml, controllers/install/binoculars_controller_e2e_test.go, controllers/install/executor_controller_e2e_test.go
@Sharpz7 brought up this linter issue so I added to our linter and fixed it.  
This way we can discover issues like this consistently among different developers.
=> fix staticheck and add to linter

controllers/install/binoculars_controller.go, controllers/install/constants.go, controllers/install/executor_controller.go
Secret name should match the secretName in the volume config.  Otherwise, you won't be able to mount the secret.
=> deployment fix

config/rbac/role.yaml, controllers/install/armadaserver_controller.go, controllers/install/armadaserver_controller_test.go
Finalizers are only required for ClusterRole and ClusterRoleBinding and those are required for binoculars and executor.
=> remove finalizers from armada server

.github/workflows/build-release-images.yml, .github/workflows/upload-docker-images.yml, .goreleaser.yaml, CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE, MAINTAINERS.md
Build Operator images using GoReleaser, then push built images to Docker Hub.
Note that the actual Docker Hub push only happens in `mainr` branch changes, so this PR will have to be merged to verify the whole build and push works. The build currently works in non-main branches, and image artifacts are successfully uploaded to GH Actions.
=> WIP: Github Actions for publishing Operator images (#2089)

controllers/install/armadaserver_controller.go
Fix Bash syntax error in pulsar-wait script.  Use official Apache Pulsar image to run `bin/pulsar-admin`.
=> Fix syntax error in pulsar-wait; use Pulsar image for admin use.

Makefile, README.md, dev/tls/webhooks_csr.conf
So far this PR seems to enable us to execute `make run` without the need to disable webhooks. In the logs it appears that webhooks are properly registered for each kind. However, I haven't been able to gather any evidence that the webhooks are actually executing when creating resources via `kubectl apply`. Still working on that...
=> Fix/Enable webhooks to Run in our Dev Cluster

.editorconfig, .github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/release_rc.yml, .github/workflows/test.yml
┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-458) by [Unito](https://www.unito.io)
=> feat: standardize ci

.github/workflows/ci.yml
The "All required checks done" CI job has been designed to be a required check, but GitHub considers it successful when it's skipped, and it gets skipped when some of the jobs it depends on fail.
This PR fixes that by always running the job and checking the results of all the jobs it depends on.
Example runs:
- [all jobs successful](https://github.com/jgiannuzzi/fasttrackml/actions/runs/5835414192)
- [some jobs failed](https://github.com/jgiannuzzi/fasttrackml/actions/runs/5835422840)
┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-659) by [Unito](https://www.unito.io)
=> ci: Fix "All required checks done" CI job to never be skipped

api/install/v1alpha1/armadaserver_types.go, api/install/v1alpha1/binoculars_types.go, api/install/v1alpha1/lookout_types.go, api/install/v1alpha1/scheduler_types.go, config/crd/bases/install.armadaproject.io_armadaservers.yaml, config/crd/bases/install.armadaproject.io_binoculars.yaml, config/crd/bases/install.armadaproject.io_lookouts.yaml, config/crd/bases/install.armadaproject.io_schedulers.yaml, internal/controller/install/armadaserver_controller.go, internal/controller/install/binoculars_controller.go, internal/controller/install/lookout_controller.go, internal/controller/install/scheduler_controller.go
Certmanager is capable of setting it's own default issuer. Armada operator requires that `.Spec.ClusterIssuer` is supplied and hardcodes cluster issuer annotations. This precludes the ability to rely on certmanager defaults.
This PR makes `ClusterIssuer` optional, and only attaches cluster issuer annotations when `ClusterIssuer` is supplied.
=> feat: make ClusterIssuer optional to allow certmanager defaults

internal/controller/install/scheduler_controller.go, internal/controller/install/scheduler_controller_test.go
This is a fix for a segfault that occurs when resources are nil in the scheduler spec. The current code tries to dereference *scheduler.Spec.Resources outside of the conditional that checks for nil.
Follow up on https://github.com/armadaproject/armada-operator/pull/298 with unit tests since @jpoler is no longer responsible for our Armada deployment.
=> fix: Avoid segfault when scheduler resources is nil

internal/controller/install/armadaserver_controller.go, internal/controller/install/eventingester_controller.go, internal/controller/install/lookout_controller.go, internal/controller/install/lookoutingester_controller.go, internal/controller/install/scheduler_controller.go, internal/controller/install/scheduleringester_controller.go
We ran into issues where we were specifying image pull secrets for service accounts but they were not effective since the deployments did not reference the service accounts.
Unfortunately the unit tests use pretty broad mock assertions so this does not impact the unit tests.
=> fix: Reference service accounts in deployments

internal/controller/install/common_helpers.go, internal/controller/install/common_helpers_test.go
c# Pull Request Template
This is a follow up to https://github.com/armadaproject/armada-operator/pull/316
Even after those changes we found the armada operator controller wasn't syncing image pull secrets to service accounts that it created. After looking further I noticed that the reconciliation code does nothing with service accounts.
Unit test added and tested on k8s 1.29
=> fix: Actually reconcile service accounts

internal/controller/install/lookout_controller.go, internal/controller/install/lookout_controller_test.go, internal/controller/install/scheduler_controller.go, internal/controller/install/scheduler_controller_test.go
We run a fork of lookout with custom schema migrations and we had issues with k8s pulling our custom image because the service account configurations were not propagated to the migration pods. 
Tested with a custom lookout image in our container registry and a service account with image pull secrets.
=> fix: Run migrations with service accounts

internal/controller/install/scheduler_controller.go
This PR fixes the issue where the scheduler installed by the operator misses the Pulsar config in order to authenticate to Pulsar.
This PR adds the Pulsar volume and volume mount to the scheduler deployment in the scheduler controller.
The change is because of the missing Pulsar config in the scheduler deployment, when Pulsar config is specified in Application config.
This PR addresses an existing issue.
Please …
=> fix: add pulsar config volume mount in scheduler

README.md, dev/quickstart/armada-crs.yaml, dev/quickstart/redis.values.yaml
Fix Scheduler erroring job submission due to missing RBAC
Scheduler missing `authPermissionMapping` in Quickstart guide
To fix it
- OS:
1. Step 1
2. Step 2
3. ...
=> fix: issue where scheduler was missing permissionGroupMapping config

go.mod, internal/controller/install/armadaserver_controller.go, internal/controller/install/binoculars_controller.go, internal/controller/install/binoculars_controller_test.go, internal/controller/install/common_helpers.go, internal/controller/install/common_helpers_test.go, internal/controller/install/eventingester_controller.go, internal/controller/install/eventingester_controller_test.go, internal/controller/install/executor_controller.go, internal/controller/install/executor_controller_test.go, internal/controller/install/lookout_controller.go, internal/controller/install/lookout_controller_test.go, internal/controller/install/lookoutingester_controller.go, internal/controller/install/lookoutingester_controller_test.go, internal/controller/install/scheduler_controller.go, internal/controller/install/scheduler_controller_test.go, internal/controller/install/scheduleringester_controller.go, internal/controller/install/scheduleringester_controller_test.go, test/integration/armadaserver_controller_test.go, test/integration/lookout_controller_test.go
- Cleanup of duplicated logic and minor bugfixes
- Nothing feature-wise
- Improve stability and reusability
- No
- OS:
1. Step 1
2. Step 2
3. ...
=> chore: remove duplicated code and fix minor bugs

internal/controller/install/armadaserver_controller.go, internal/controller/install/executor_controller.go, internal/controller/install/scheduler_controller.go, internal/controller/install/scheduler_controller_test.go
Add prometheus rule for Scheduler and update prometheus rules for Server and Executor
Server, Scheduler and Executor controllers
To fix broken monitoring
- OS:
1. Step 1
2. …
=> feat: update prometheus rules for server, scheduler and executor

go.mod, internal/controller/install/lookout_controller.go, internal/controller/install/lookout_controller_test.go, internal/controller/install/scheduler_controller.go, internal/controller/install/scheduler_controller_test.go
Fixes #335
Also introduces `protocmp` as a way to make assertions on entire proto structs instead of cherry picking assertions on individual fields. This should make unit test much more robust moving forward if used.
See new unit tests
=> fix: Update pruning pods to use different labels and add unit test

internal/controller/install/common_helpers.go, internal/controller/install/lookout_controller.go, internal/controller/install/lookout_controller_test.go, internal/controller/install/scheduler_controller.go, internal/controller/install/scheduler_controller_test.go
Fixes #337 
* Reconcile scheduler pruner cron jobs
* Update logic to delete previously enabled cron jobs when pruning is disabled. Otherwise, disabling pruning does nothing and the jobs will continue to run.
See unit tests.
=> fix: Delete cronjobs when pruning disabled and actually reconcile scheduler corncobs

internal/controller/install/armadaserver_controller.go, internal/controller/install/armadaserver_controller_test.go, internal/controller/install/binoculars_controller.go, internal/controller/install/binoculars_controller_test.go, internal/controller/install/common_helpers.go, internal/controller/install/executor_controller.go, internal/controller/install/executor_controller_test.go, internal/controller/install/lookout_controller.go, internal/controller/install/lookout_controller_test.go, internal/controller/install/scheduler_controller.go, internal/controller/install/scheduler_controller_test.go
The pull request updates various controllers to add readiness & liveness probes to containers where applicable. These probes should help indicate when it is safe to cutover to new deployments. 
I cross referenced https://github.com/armadaproject/armada/tree/master/deployment (I may have found some bugs in here tho) as well as each application's config structs to understand which ports they expose. 
Fixes #334 
Added unit tests to assert the fully generated deployment with probes.
=> fix: Add liveness and readiness probes

api/install/v1alpha1/scheduler_webhook.go, api/install/v1alpha1/scheduler_webhook_test.go, internal/controller/install/armadaserver_controller.go, internal/controller/install/common_helpers.go, internal/controller/install/lookout_controller.go, internal/controller/install/lookout_controller_test.go, internal/controller/install/scheduler_controller.go, internal/controller/install/scheduler_controller_test.go
Scheduler Controller erroring due to missing defaults for Pruner
Added better checks and safe guards
Panics prevent Operator from working and reconciling as expected
- OS:
1. …
=> fix: controller panics due to missing defaults

internal/controller/install/armadaserver_controller.go, internal/controller/install/armadaserver_controller_test.go
This pull request allows users to run Armada Server in an HA manner so that it will be available during rolling upgrades.
Fixes #341 
Unit Tests & Our Environment
=> fix: Set armada server replicas from spec

internal/controller/install/lookout_controller.go, internal/controller/install/lookout_controller_test.go, internal/controller/install/scheduler_controller.go, internal/controller/install/scheduler_controller_test.go
If pruning cron jobs have misconfigured timeouts/schedules they have an opportunity to run concurrently. We should forbid that.
Unit tests
=> fix: Pruning cron jobs should forbid concurrency

.github/workflows/lint_pr.yml
Reduce permissions of the lint-pr github action.
Add a permissions block to lint-pr. This is now the recommended option in:
https://github.com/amannn/action-semantic-pull-request#installation
Recently a project has been attacked using `pull_request_target` see [full details](https://blog.yossarian.net/2024/12/06/zizmor-ultralytics-injection). This project/action is not vulnerable to that, but there is no reason for the token associated with this action to have write permissions.
n/a, improves security posture of the project.
Only affects CI; CI will test it.
Can check by looking at …
=> ci: Reduce permissions of semantic-pull-request check

.github/workflows/ci.yml
Currently, the `all-required-checks-done` job runs and succeeds `always()`, even if jobs it depends on fail, are cancelled or skipped. It succeeds even if other jobs don't. Usually, you want to block pull request merges until CI pipeline succeeds, not until it just finishes.
CI
Failed workflow before this change:
https://github.com/EnricoMi/armada-operator/actions/runs/13922761708/job/38961096882
Skipped workflow before this change:
https://github.com/EnricoMi/armada-operator/actions/runs/13924158519/job/38964210807
Cancelled workflow after this change:
https://github.com/EnricoMi/armada-operator/actions/runs/13924283498/job/38964942928
Successful run after this change:
https://github.com/EnricoMi/armada-operator/actions/runs/13924283498
=> ci: Make required checks job pass only on success

dev/quickstart/pulsar.values.yaml, hack/wait-for-deps.sh
This amends `armada-operator/dev/quickstart/pulsar.values.yaml` with some minimal setup values suggested by [Pulsar helm chart examples for minikube](https://github.com/apache/pulsar-helm-chart/blob/master/examples/values-minikube.yaml).
Specifically `diskUsageThreshold: "0.999"` (not taken from minikube example) fixes issues we see with bookie complaining about too little free disk. On Github runners, 5% of 72G is plenty of free disk for our example.
This operator is used in the end-to-end test of Armada-Spark: https://github.com/armadaproject/armada-spark/pull/31
Before this fix, we see
2025-04-11T17:07:35,565+0000 [LedgerDirsMonitorThread] ERROR org.apache.bookkeeper.util.DiskChecker - Space left on device …
=> fix: Use minimal pulsar values
