- PROJECT
- apis/install/v1alpha1/webhook_suite_test.go
- config/crd/bases/install.armadaproject.io_binoculars.yaml
- config/crd/bases/install.armadaproject.io_executors.yaml
Missed Project and webhook code for binoculars.
> binocular missing webhook

- config/samples/install_v1alpha1_armadaserver.yaml
> config sample for server

- controllers/install/lookout_controller.go
- controllers/install/lookout_controller_test.go
- test/integration/lookout_controller_e2e_test.go
> All tests pass with migration. Woohoo!

- .gitmodules
- Makefile
- README.md
- config/samples/deploy_armada.yaml
- config/samples/install_v1alpha1_armadaserver.yaml
- config/samples/install_v1alpha1_eventingester.yaml
- config/samples/install_v1alpha1_lookoutingester.yaml
- dev/helm-charts/postgres_bitnami_values.yaml
- dev/helm-charts/pulsar_apache_values.yaml
- dev/helm-charts/redis_bitnami_values.yaml
- dev/start.bash
- dev/stop.bash
Starting point for postgres. If we can agree on the how of what I'm doing then hopefully adding on redis, pulsar, etc won't be too difficult.
> Create a dev cluster from the makefile, provides postgresql, pulsar, redis

- Makefile
- config/rbac/role.yaml
- config/samples/deploy_armada.yaml
- config/samples/deploy_executor_cluster.yaml
- controllers/install/lookout_controller.go
- dev/helm-charts/redis_bitnami_values.yaml
Getting some pieces working so I can deploy to kind.
> Integration

- Makefile
- dev/helm-charts/pulsar_apache_values.yaml
> WIP: Add prometheus to dev cluster

- Makefile
- config/samples/prometheus.yaml
> Use the prometheus operator to install/run prometheus in our dev cluster

- README.md
> Update README.md to something approaching good

- controllers/install/armadaserver_controller.go
- controllers/install/binoculars_controller.go
- controllers/install/binoculars_controller_test.go
- controllers/install/common_helpers.go
- controllers/install/common_helpers_test.go
- controllers/install/eventingester_controller.go
- controllers/install/executor_controller.go
- controllers/install/lookout_controller.go
- controllers/install/lookout_controller_test.go
- controllers/install/lookoutingester_controller.go
> Enable mutating function in Reconcilers by extracting CommonComponents

- controllers/install/armadaserver_controller.go
- controllers/install/armadaserver_controller_test.go
- controllers/install/binoculars_controller.go
- controllers/install/binoculars_controller_test.go
- controllers/install/common_helpers.go
- controllers/install/lookout_controller.go
- controllers/install/lookout_controller_test.go
we need to serve all paths, not just /api/...
> Remove the grpc ingress -- not present in the helm deployment. Also,

- controllers/install/armadaserver_controller.go
- controllers/install/binoculars_controller.go
- controllers/install/common_helpers.go
- controllers/install/common_helpers_test.go
- controllers/install/executor_controller.go
- controllers/install/lookout_controller.go
┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-163) by [Unito](https://www.unito.io)
> allow combined label sources in Ingress, PrometheusRule, ServiceMonitor

- controllers/install/armadaserver_controller.go
- controllers/install/lookout_controller.go
- controllers/install/lookout_controller_test.go
┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-165) by [Unito](https://www.unito.io)
> custom prometheus rule for server

- .github/workflows/go.yml
- codecov.yml
┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-239) by [Unito](https://www.unito.io)
> chore: Disable the code-cov step

- controllers/install/armadaserver_controller.go
- controllers/install/common_helpers.go
- controllers/install/common_helpers_test.go
- controllers/install/eventingester_controller.go
- controllers/install/lookoutingester_controller.go
- controllers/install/scheduleringester_controller.go
┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-230) by [Unito](https://www.unito.io)
> feat: Pulsar ca and token volume

- .github/workflows/release-rc.yml
- config/rbac/role.yaml
- controllers/install/scheduler_controller.go
┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-246) by [Unito](https://www.unito.io)
> fix: invalid creds in release-rc.yml and minor bug with scheduler rbac

- .github/workflows/release.yml
- .github/workflows/release_rc.yml
Thanks @dave-gantenbein for your assistance :)
┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-250) by [Unito](https://www.unito.io)
> fix: add environment to release workflows

- .github/workflows/release_rc.yml
┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-251) by [Unito](https://www.unito.io)
> fix: remove --skip-publish in release rc workflow

- .goreleaser.yaml
┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-253) by [Unito](https://www.unito.io)
> fix: templating for release disable in goreleaser config

- .github/workflows/release.yml
- .github/workflows/release_chart.yml
- charts/armada-operator/Chart.yaml
- charts/armada-operator/values.yaml
- scripts/update_chart.sh
┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-460) by [Unito](https://www.unito.io)
> fix: ci fixes

- .github/workflows/release.yml
- .goreleaser.yaml
┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-461) by [Unito](https://www.unito.io)
> fix: ci release

- .github/workflows/release.yml
┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-464) by [Unito](https://www.unito.io)
> fix: helm release job version

- .github/workflows/release.yml
┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-465) by [Unito](https://www.unito.io)
> fix: add checkout depth for helm release job

- Makefile
Partially fixes https://github.com/armadaproject/armada/issues/3720
> chore: update get-armadactl make target not to cause git diffs

- Makefile
- api/install/v1alpha1/common.go
- dev/crd/out.md
- dev/quickstart/armada-crs.yaml
- dev/quickstart/example-job-preemptible.yaml
- dev/quickstart/preemptible-priority-class.yaml
- dev/quickstart/priority-class.yaml
- dev/quickstart/redis.values.yaml
- hack/kind-config.yaml
- hack/wait-for-deps.sh
- internal/controller/install/armadaserver_controller.go
- internal/controller/install/common_helpers.go
- internal/controller/install/scheduler_controller.go
Changelog:
* fix Lookout cancel job bug
* slim down redis to 1 replica
* rename postgres -> postgresql
* update Armada components to latest
* remove unneeded code
* fix issue with `armadactl get scheduling-report`
> feat: fix lookout cancellation bug; slim down redis; rename postgres -> postgresql

- README.md
> fix: Fix link to CRs

- README.md
- dev/quickstart/armada-crs.yaml
This pull request cleans up documentation so that it is current with recent versions of Armada. 
We are using auth in production.
> docs: Cleanup permission group mappings

- internal/controller/install/common_helpers.go
- internal/controller/install/lookout_controller.go
- internal/controller/install/lookout_controller_test.go
- internal/controller/install/scheduler_controller.go
- internal/controller/install/scheduler_controller_test.go
Bug Fixes
* Fixes an issue where the scheduler cron job would never get created due to variable shadowing
* Fixes an issue where the scheduler cron job would run with an invalid command
* Fixes an issue where cron job updates wouldn't get synced
Enhancements
* Plumbs service accounts to cron jobs
> fix: pruning related issues

- Makefile
- dev/quickstart/kube-prometheus-stack.values.yaml
- OS:
1. Step 1
2. Step 2
3. ...
> chore: update external dependency versions of armada

- Makefile
- dev/quickstart/postgres.values.yaml
- dev/quickstart/pulsar.values.yaml
Fix broken quickstart.
Bitnami removed a lot of public images, including Postgres, which broke the quickstart.
To make quickstart working again.
- OS:
1. Step 1
2. Step 2
3. …
> feat: migrate postgres to non-bitnami image for quickstart
